name: Fly Deploy

on:
    push:
        branches:
            - master

concurrency:
    group: ci-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        environment: production
        if: ${{ !contains(github.event.head_commit.message, 'NO_DEPLOY') }}
        steps:
            - uses: actions/checkout@v3

            - name: ğŸ› ï¸ Setup Fly
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: ğŸš€ Deploy To Fly
              run: |
                  flyctl secrets set DJANGO_SECRET_KEY='${{ secrets.DJANGO_SECRET_KEY }}'
                  flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
